In [1]:
!pip install transformers

     |████████████████████████████████| 778kB 3.4MB/s 
     |████████████████████████████████| 890kB 15.7MB/s 
     |████████████████████████████████| 1.1MB 25.1MB/s 
     |████████████████████████████████| 3.0MB 38.1MB/s 
  Created wheel for sacremoses: filename=sacremoses-0.0.43-cp36-none-any.whl size=893260 sha256=89c24c5fd412e2f980468345dc915c244644544adcce3772997aea6d017f4f53
  Stored in directory: /root/.cache/pip/wheels/29/3c/fd/7ce5c3f0666dab31a50123635e6fb5e19ceb42ce38d4e58f45
Successfully built sacremoses


In [4]:
import tensorflow as tf; tf.__version__ # 2.0.0
import torch; torch.__version__ # 1.3.1
import transformers;transformers.__version__ # 2.10.0

'3.0.2'

In [2]:
from transformers import AutoModel, AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained('bert-base-chinese')
model = AutoModel.from_pretrained('bert-base-chinese')

# 向量编码和向量相似性展示

In [6]:
# tensor([[ 101, 3217, 4697,  679, 6230, 3236,  102]])
input_ids = tokenizer.encode('春眠不觉晓', return_tensors='pt')
last_hidden_state, _ = model(input_ids) # shape (1, 7, 768)
v = torch.mean(last_hidden_state, dim=1) # shape (1, 768)

In [13]:
import numpy as np

def sentence_embedding(sentence):
    input_ids = tokenizer.encode(sentence, return_tensors='pt')
    hidden_states, _ = model(input_ids)
    return torch.mean(hidden_states, dim=1)

sentences = ['春眠不觉晓','大梦谁先觉','浓睡不消残酒','东临碣石以观沧海']

with torch.no_grad():
    vs = [sentence_embedding(sentence).numpy() for sentence in sentences]
    nvs = [v / np.linalg.norm(v) for v in vs] # normalize each vector
    print(f"np.array(nvs).shape:{np.array(nvs).shape}")
    m = np.array(nvs).squeeze(1) # shape (4, 768)
    print(np.around(m @ m.T, decimals=2)) # pairwise cosine similarity

np.array(nvs).shape:(4, 1, 768)
[[1.   0.75 0.83 0.57]
 [0.75 1.   0.72 0.51]
 [0.83 0.72 1.   0.58]
 [0.57 0.51 0.58 1.  ]]
